-- mapped.lua :: a sti-mapped box

--[[
  Copyright © 2019 Kazhnuz

  Permission is hereby granted, free of charge, to any person obtaining a copy of
  this software and associated documentation files (the "Software"), to deal in
  the Software without restriction, including without limitation the rights to
  use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
  the Software, and to permit persons to whom the Software is furnished to do so,
  subject to the following conditions:

  The above copyright notice and this permission notice shall be included in all
  copies or substantial portions of the Software.

  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
  FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
  COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
  IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
  CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
]]

local cwd   = (...):gsub('%.mapped$', '') .. "."
local Box3D = require(cwd .. "parent")

local MappedBox = Box3D:extend()

function MappedBox:new(owner, x, y, z, w, h, d)
  self.x = x
  self.y = y
  self.z = z

  MappedBox.super.new(self, owner, w, h, d)
  self.haveLine = false
end

function MappedBox:drawTextureContent()
  local tx, ty = self.x, self.y - (self.z + self.d)
  core.debug:print("mappedbox", "getting map layers at position " .. tx .. ";" .. ty)
  love.graphics.push()
  love.graphics.origin()
  love.graphics.translate(math.floor(-tx), math.floor(-ty))

  self.world:drawMap()

  love.graphics.pop()
end


return MappedBox
