local Battler = require("scenes.battlesystem.actors.battler")
local Ennemy = Battler:extend()

local gui         = require "game.modules.gui"

function Ennemy:new(world, x, y, owner)
  Ennemy.super.new(self, world, x, y, 0)
  self.isEnnemy = true
  self.owner = owner

  self.actionPerTurn = 2
end

function Ennemy:draw()
  local x, y = self.world.map:gridToPixel(self.x, self.y, true)
  love.graphics.setColor(1, 0, 0, 1)
  love.graphics.rectangle("fill", x - 8, y - 32, 16, 32)
  love.graphics.setColor(1, 1, 1, 1)

  self.owner:drawHUD(x - 14, y - 38)

  if (self.isSelected) then
    local height = 32
    self.assets.images["cursorpeak"]:draw(x - 7, y - 24 - 32)
  end
end

function Ennemy:getStats()
  return self.data.stats
end

return Ennemy
